name: Automated Cherry-Pick Engine

on:
  pull_request:
    types: [labeled, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  cherry-pick:
    if: github.event.pull_request.merged == true && contains(toJSON(github.event.pull_request.labels.*.name), 'cherry-pick to ')
    uses: bunnam988/build_tools_workflows/.github/workflows/cherry-pick.yml@develop
    with:
      raw_labels: ${{ toJSON(github.event.pull_request.labels) }}
    secrets:
      CROSS_REPO_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
