name: Topic Gatekeeper

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - 'release/**'
      - 'support/**'
  pull_request_review:
    types: [submitted]

jobs:
  run-shared-gatekeeper:
    uses: bunnam988/build_tools_workflows/.github/workflows/gatekeeper.yml@develop
